### ISSUE TITLE
Program paniced on automate command.

### ISSUE THREAD

**Issue by kenjoe41** [BishopFox/sj#28]
**Describe the bug**

Program paniced while running the automate command with the file input. I am running golang 1.23.1

**To Reproduce**

A code block containing the command executed with output:

```bash
$ sj automate -l [FILE HERE] -q
```
It printed some description but panicked at some point with,
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x817ac8]

goroutine 1 [running]:
github.com/BishopFox/sj/cmd.SwaggerRequest.AddParametersToRequest({{0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, 0x0}, 0xc000266d20, {0x0, 0x0, ...}, ...}, ...)
	/home/kenjoe41/go/pkg/mod/github.com/!bishop!fox/sj@v0.0.0-20240827020333-2877384d5441/cmd/utils.go:219 +0x88
github.com/BishopFox/sj/cmd.SwaggerRequest.BuildDefinedRequests({{0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, 0x0}, 0xc000266d20, {0x0, 0x0, ...}, ...}, ...)
	/home/kenjoe41/go/pkg/mod/github.com/!bishop!fox/sj@v0.0.0-20240827020333-2877384d5441/cmd/utils.go:167 +0x1e5
github.com/BishopFox/sj/cmd.SwaggerRequest.IterateOverPaths({{0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0, {0x0, 0x0, ...}, ...}, ...)
	/home/kenjoe41/go/pkg/mod/github.com/!bishop!fox/sj@v0.0.0-20240827020333-2877384d5441/cmd/utils.go:149 +0x629
github.com/BishopFox/sj/cmd.GenerateRequests({0xc0001e4000?, 0xc00006a2b0?, 0x0?}, {{0x9b2dc0, 0xc000002300}, 0x9352a0, {0x0, 0x0}, 0x0})
	/home/kenjoe41/go/pkg/mod/github.com/!bishop!fox/sj@v0.0.0-20240827020333-2877384d5441/cmd/utils.go:104 +0x4fe
github.com/BishopFox/sj/cmd.init.func4(0xc0000f8a00?, {0x8ec433?, 0x4?, 0x8ec437?})
	/home/kenjoe41/go/pkg/mod/github.com/!bishop!fox/sj@v0.0.0-20240827020333-2877384d5441/cmd/automate.go:54 +0x39b
github.com/spf13/cobra.(*Command).execute(0xc918e0, {0xc0000abf50, 0x3, 0x3})
	/home/kenjoe41/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc91600)
	/home/kenjoe41/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/home/kenjoe41/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/BishopFox/sj/cmd.Execute()
	/home/kenjoe41/go/pkg/mod/github.com/!bishop!fox/sj@v0.0.0-20240827020333-2877384d5441/cmd/root.go:55 +0x1a
main.main()
	/home/kenjoe41/go/pkg/mod/github.com/!bishop!fox/sj@v0.0.0-20240827020333-2877384d5441/main.go:6 +0xf
```

**Desktop (please complete the following information):**
 - OS: Debian Linux

**Comment by twest-bf** [comment]
Can you confirm which version of sj you are using?

```bash
$ sj -v
```

Just from looking at the error message it seems like you're using an older version so it's hard to say what is causing the error without more information.

**Comment by kenjoe41** [comment]
I updated to the latest new version and it's all good.
